/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import org.austral.game.chess.DefaultGameEngine
import edu.austral.dissis.chess.gui.CachedImageResolver
import edu.austral.dissis.chess.gui.DefaultImageResolver
import edu.austral.dissis.chess.gui.GameView
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage
import org.austral.game.checkers.CheckersGameEngine
import org.austral.game.checkers2.CheckersGameEngine2
import org.austral.game.checkers2.CheckersGameFactory
import org.austral.game.chess.ChessGameFactory
import org.austral.game.commons.CustomGameEngine


fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
    private val gameEngine = CustomGameEngine(CheckersGameFactory());
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun init() {
        super.init()
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle

        val root = GameView(imageResolver)

        primaryStage.scene = Scene(root)
        primaryStage.show()
    }

    override fun stop() {
        super.stop()
    }
}